### ISSUE TITLE
When will Frimgur be released? + suggestions

### ISSUE THREAD

**Issue by Destroyinator69420** [Bombe/frimgur#1]
Hello Bombe, I heard about your new freenet plugin on Freenet FIrst Steps. When can I expect a freesite so I can install it as a plugin and try it out. I really like the idea of a decentralized imgur for freenet.

I think that the speed of requesting the images could be increased if there was an option to have frimgur pages open in the plugin while the images themselves are compressed with the Java implementation LZMA2 on ultra settings from LZMA SDK, then the plugin extracts them before showing them to the user. LZMA SDK is in the public domain. It would also be nice to see a WoT based comments section along with the option to export to a read only freesite.

**Comment by Bombe** [comment]
Hi! There is a freesite: `USK@9CaRpvZRmOKeFbkmtyZ6t5AmO19xCpz1~HNoaxqZBY0,R1nwUpYNMOVgs7iUN9rAyVo-9wYuWOLwrfV1RTRiG~E,AQACAAE/frimgur/2/` – and there is also already a release! Unfortunately, I think the only place it’s linked from is Frimgur’s profile page on Sone so yeah, that’s kind of hard to find. 😁 I’ll include it in my blog which then should lead to all the search engines including it as well.

**Comment by Bombe** [comment]
As for the rest of your suggestions: I have no idea what you’re trying to say. Right now Frimgur’s only job is to insert images from the clipboard. The compression of the images is determined by the software doing the actual pasting; i.e. in my tests Firefox always compresses the clipboard contents as PNG. Frimgur does not recompress anything, it inserts the blob it gets from the browser.

Commenting and/or publishing image pages is currently not planned.
